directory: /app/data/music
library: /root/.config/beets/library.db

import:
  write: yes
  copy: yes
  move: no
  log: /app/data/logs/beets-import.log
  timid: no
  quiet: no
  quiet_fallback: asis
  autotag: yes

match:
  strong_rec_thresh: 0.15
  medium_rec_thresh: 0.40
  preferred:
    countries: []
    media: ['Digital Media', 'CD']
    original_year: no

plugins:
  - musicbrainz
  - fetchart
  - embedart
  - chroma

fetchart:
  auto: yes
  sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart

embedart:
  auto: yes
  ifempty: no

ui:
  color: no

acoustid:
  apikey: ""
